image: python:3.11-slim

stages:
  - test
  - deploy

cache:
  - key: pip-cache
    paths:
      - .pip-cache/
  - key: coverage-fixed-key 
    paths:
      - htmlcov/

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

# 1. Run Tests and calculate coverage
run_tests:
  stage: test
  tags:
    - shared-docker
  variables:
    NUMBA_DISABLE_JIT: "1"
  script:
    - apt-get update && apt-get install -y libexpat1 libgomp1
    - pip install --upgrade pip
    - pip install pytest pytest-cov ".[test]"
    - python -m pytest --cov=pyguidos tests/ --cov-report term-missing --cov-report html
  coverage: '/(?i)total.*? (100(?:\.0+)?%|[1-9]?\d(?:\.\d+)?%)/'
  artifacts:
    when: always
    paths:
      - htmlcov/
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_COMMIT_BRANCH == "main"
      when: always

# 2. Build and Deploy Documentation (GitLab Pages)
pages:
  stage: deploy
  tags:
    - shared-docker
  needs:
    - job: run_tests
      artifacts: true  # Explicitly tell GitLab to bring the htmlcov folder over
      optional: true
  script:
    - apt-get update && apt-get install -y libexpat1
    - pip install --upgrade pip
    - pip install sphinx pydata-sphinx-theme ".[notebooks,test]" 
    - sphinx-build -b html docs public
    - |
      if [ -d "htmlcov" ]; then
        echo "Coverage data found. Moving to public/coverage..."
        mkdir -p public/coverage
        cp -rf htmlcov/* public/coverage/
      else
        echo "ERROR: htmlcov directory not found in current workspace!"
        ls -la  
        exit 1  
      fi
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always

# 3. Build and Publish Package to PyPI
publish_pypi:
  stage: deploy
  tags:
    - shared-docker
  needs:
    - job: run_tests
      artifacts: false 
  script:
    - apt-get update && apt-get install -y libexpat1
    - pip install --upgrade pip
    - pip install build twine
    - python -m build
    - TWINE_USERNAME=__token__ TWINE_PASSWORD=${PYPI_ID_TOKEN} python3 -m twine upload dist/*
  rules:
    - if: $CI_COMMIT_TAG
      when: always