# pyproject.toml

[project]
name = "pyguidos" 
version = "0.1.0" 
authors = [
  { name="Giovanni Caudullo", email="your.email@example.com" },
]
description = "pyguidos"
readme = "README.md" 
requires-python = ">=3.8" 
keywords = ["utility", "functions", "example", "pyguidos"] 
classifiers = [
    "Development Status :: 3 - Alpha", 
    "Intended Audience :: Developers",
    "License :: OSI Approved :: EUPL v. 1.2", 
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Utilities", 
    "Topic :: Scientific/Engineering :: GIS",
]

dependencies = [
]

[project.optional-dependencies]
notebooks = [
    "pandas>=2.3",
    "matplotlib>=3.5",
    "jupyterlab>=4.1",
    "numpy>=1.26",
    "rasterio>=1.4"
]

test = [
    "pytest>=6.0",
    "pytest-mock>=3.0", 
    "numpy>=1.26",      
    "rasterio>=1.4"     
]

[build-system]
requires = ["setuptools>=61.0"]  
build-backend = "setuptools.build_meta"


# --- Pytest Configuration ---
[tool.pytest.ini_options]

markers = [
    "integration: marks tests as integration tests (requiring external dependencies like GWB)",
]

addopts = "--strict-markers -s -v"

testpaths = [
    "tests",
]

python_files = "test_*.py"


