import time
from pathlib import Path
import csv
import matplotlib.pyplot as plt

import rasterio
from rasterio.enums import ColorInterp
import numpy as np

from . import engine
from . import utils
from . import checks
from . import TEMPL_DIR


def frag_change(
    in_tiff_t1,
    in_tiff_t2,
    outdir=None,
    statists=True,
    stat_files=True,
    verb=False
    ):
    """
    Performs a comparative Fragmentation Change analysis using two structural 
    fragmentation rasters (Time A/T1 and Time B/T2) generated by Guidos.

    It computes pixel-by-pixel class transitions across a 7-tier matrix overlay, 
    tracks localized delta variations, and compiles comprehensive global matrix 
    statistics reporting land-cover and connectivity class dynamics.

    Parameters
    ----------
    in_tiff_t1 : str or Path
        Path to the initial time-step Fragmentation GeoTIFF (Time A / T1). 
        Must be a valid Guidos 'GTB_FOS' output.
    in_tiff_t2 : str or Path
        Path to the subsequent time-step Fragmentation GeoTIFF (Time B / T2). 
        Must be a valid Guidos 'GTB_FOS' output matching T1's spatial extent.
    outdir : str or Path, optional
        Directory for generated output files. Defaults to the directory of 
        the initial input file (`in_tiff_t1`).
    statists : bool, optional
        If True (default), computes and returns change transition statistics.
    stat_files : bool, optional
        If True (default) and `statists` is True, writes statistics reports 
        to explicit `.txt`, `.csv`, and `.png` histogram files.
    verb : bool, optional
        If True, prints execution pipeline progress messages. Default is False.

    Returns
    -------
    dict or None
        If `statists` is True, returns a nested dictionary containing:
        - 'output paths' (dict or None): Paths to generated files
          ('path tif', 'path txt', 'path csv', 'path png').
        - 'input stats' (dict): Extracted raw pixel frequencies for T1 and T2 
          (Foreground, Background, Missing, Special classes).
        - 'output stats' (dict): Class frequency mappings, connectivity indices 
          (avcon, fad_av) for both time steps, and aggregated transition matrices.
        Returns None if `statists` is False.

    Output Files
    ------------
    - FOS_change.tif : Categorical fragmentation change layer grid.
    - FOS_change.txt : Detailed structural analysis change matrix text report.
    - FOS_change.csv : Tabular cell count statistics with delta values.
    - FOS_change.png : Connectivity change frequency distribution bar chart.
    """
    start_time = time.time()
    
    # Log
    utils.log_msg(verb, "[   START   ]  Verifying input raster...")

    # Initialize Paths and Metadata
    in_tiff1 = Path(in_tiff_t1)
    in_tiff2 = Path(in_tiff_t2)
    outdir = Path(outdir) if outdir else in_tiff1.parent
    outname = "FOS_change"
    info1 = utils.get_raster_info(in_tiff1)
    info2 = utils.get_raster_info(in_tiff2)

    # Input Geotiff validations
    checks.validate_fchmaps_input(info1, info2)
    
    # Log
    utils.log_msg(verb, "[    OK     ]  Input raster verified.")

    try:
        # Log
        utils.log_msg(verb, "[   START   ]  Computing Fragmentation Change...")
        
        # Output Geotiff info
        tag_descr = info1["tag"]
        tag_descr = tag_descr.replace("GTB_FOS","GTB_FOSCHANGE")
        cmap_path = TEMPL_DIR / "frag_change_colormap.txt"
        out_tiff = outdir / f"{outname}.tif"
        _, color_map = utils.get_colormap(cmap_path)
        tags = {"TIFFTAG_IMAGEDESCRIPTION": tag_descr,
                "TIFFTAG_SOFTWARE": "pyGuidos"}
        
        # Compute Frag Change
        change_matrix = np.zeros((107, 107), dtype=np.int64)
        with rasterio.open(in_tiff1) as src_a, rasterio.open(in_tiff2) as src_b:
            out_profile = info1["profile"]
            out_profile.update(tiled=True)
        
            # BigTIFF threshold optimization
            estimated_gb = (info1["rows"] * info1["cols"]) / (1024**3)
            out_profile.update(bigtiff="YES" if estimated_gb > 3.8 else "NO")
        
            with rasterio.open(out_tiff, "w", **out_profile) as dst:
                for ij, window in src_a.block_windows():
                    chunk_a = src_a.read(1, window=window)
                    chunk_b = src_b.read(1, window=window)
        
                    # Computes raster AND statistics
                    chunk_out = engine.compute_fos_change(chunk_a, 
                                                          chunk_b, 
                                                          change_matrix, 
                                                          statists)
                    # Write the chunk output
                    dst.write(chunk_out, 1, window=window)
        
                dst.colorinterp = [ColorInterp.palette]
                dst.write_colormap(1, color_map)
                dst.update_tags(**tags)
     
        # Log
        utils.log_msg(verb, "[    OK     ]  Fragmentation Change computed.")
 
        # Statistics and Reporting
        stats_dict = None
        if statists:
            utils.log_msg(verb, "[   START   ]  Generating statistics...")        
            
            # Computing statistics
            stats_dict = _get_frag_change_stats(frag_chan_tiff = out_tiff, 
                                                ch_matrix = change_matrix,
                                                tiff1 = in_tiff1,
                                                tiff2 = in_tiff2,
                                                out_file = stat_files,
                                                out_dir = outdir)    
            
        # Computational time and log
        time_str = utils.running_time(start_time, time.time())
        
        if statists:
            txt_file = txt_file = outdir / f'{outname}.txt'
            utils.update_time_line(txt_file, time_str)
            utils.log_msg(verb, "[    OK     ]  Statistics complete")
        
        utils.log_msg(verb, f"\n>>> Fragmentation Change task finished in {time_str}") 

        return stats_dict

    except Exception as e:
        print(f"Error during run: {e}")
        raise # Still show the error




#############

def _get_frag_change_stats(frag_chan_tiff, 
                           ch_matrix,
                           tiff1,
                           tiff2,
                           out_file,
                           out_dir):
    """
    Get the Fragmentation Change statistics.    
    """
    
    # Land stats computation
    group_land = [range(0,101), [101, 105, 106], [102]]
    ch_matrix_land, tot_land_A, tot_land_B = aggregate_change_matrix(ch_matrix, group_land)
    
    fgrnd_AB = ch_matrix_land[0,0]
    Uarea_AB = ch_matrix_land[0:2,0:2].sum()
    
    tots_land_A = ch_matrix_land.sum(axis=1)
    fgrnd_A = tots_land_A[0]
    bgrTT_A = tots_land_A[1]
    bgrnd_A = ch_matrix[101, :].sum()
    bgsp3_A = ch_matrix[105, :].sum()
    bgsp4_A = ch_matrix[106, :].sum() 
    miss_A = tots_land_A[2]

    tots_land_B = ch_matrix_land.sum(axis=0)
    fgrnd_B = tots_land_B[0]
    bgrTT_B = tots_land_B[1]
    bgrnd_B = ch_matrix[:, 101].sum()
    bgsp3_B = ch_matrix[:, 105].sum()
    bgsp4_B = ch_matrix[:, 106].sum()     
    miss_B = tots_land_B[2]

    # Class stats computation
    group_clas = [[101, 105, 106], range(0,10), range(10,40), range(40,60), range(60,90), range(90,101)]
    ch_matrix_clas, tot_clas_A, tot_clas_B  = aggregate_change_matrix(ch_matrix, group_clas)
    
    tots_class_A = ch_matrix_clas.sum(axis=1)
    rare_A = tots_class_A[1]
    patchy_A = tots_class_A[2]
    trans_A = tots_class_A[3]
    domin_A = tots_class_A[4]
    inter_A = tots_class_A[5]

    tots_class_B = ch_matrix_clas.sum(axis=0)
    rare_B = tots_class_B[1]
    patchy_B = tots_class_B[2]
    trans_B = tots_class_B[3]
    domin_B = tots_class_B[4]
    inter_B = tots_class_B[5]
    
    diagonal = np.diag(ch_matrix_clas)[1:6].sum()
    upper_pxl = np.triu_indices(ch_matrix_clas.shape[0], k=1)
    increase = ch_matrix_clas[upper_pxl].sum()
    lower_pxl = np.tril_indices(ch_matrix_clas.shape[0], k=-1)
    decrease = ch_matrix_clas[lower_pxl].sum()

    # Calculate Connectivity indices
    tots_ch_matrix_A = ch_matrix.sum(axis=1)
    sum_prod_A = np.sum(np.arange(101) * tots_ch_matrix_A[0:101])
    ruarea_A = fgrnd_A + bgrTT_A
    avcon_A = sum_prod_A / ruarea_A
    fad_av_A = sum_prod_A / fgrnd_A
    
    tots_ch_matrix_B = ch_matrix.sum(axis=0)
    sum_prod_B = np.sum(np.arange(101) * tots_ch_matrix_B[0:101])
    ruarea_B = fgrnd_B + bgrTT_B
    avcon_B = sum_prod_B / ruarea_B
    fad_av_B = sum_prod_B / fgrnd_B
    
    # Fragmentation Change pixel counting
    with rasterio.open(frag_chan_tiff) as src:
        fragch_data = src.read(1)
        fragch_pxl_freq = utils.get_pxl_freq(fragch_data)
    
    # Get Frag parameters
    minfo = utils.get_raster_info(tiff1)
    tag = minfo["tag"]
    tool_params = utils.get_tool_parameters(tag)
    method, fclasses = tool_params["method"].split('_')
    window_size = int(tool_params["wsize"])
    out_name = "FOS_change"
    
    # Fragmentation Change stats
    H_decr = sum(fragch_pxl_freq[i] for i in range(0,80))
    M_decr = sum(fragch_pxl_freq[i] for i in range(80,90))
    L_decr = sum(fragch_pxl_freq[i] for i in range(90,99))
    Insign = sum(fragch_pxl_freq[i] for i in range(99,102))
    L_incr = sum(fragch_pxl_freq[i] for i in range(102,111))
    M_incr = sum(fragch_pxl_freq[i] for i in range(111,121))
    H_incr = sum(fragch_pxl_freq[i] for i in range(121,201))

    if out_file:

        ### CSV Export ###
        csv_file = out_dir / f'{out_name}.csv'
        with open(csv_file, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['pixel_value', 'Delta_FAD', 'pixel_count', 'foreground_proportion'])
            for v in range(201):
                pct = ((fragch_pxl_freq[v] / fgrnd_AB) * 100)
                d_FAD = 100 - v
                writer.writerow([v, d_FAD, fragch_pxl_freq[v], f"{pct:.6f}"])

        ### Histogram PNG figure ###

        # X & Y values
        pixel_values = []
        frag_chag_pxl_prop = []
        for i in range(200, -1, -1):
            pixel_values.append(100 - i)
            frag_chag_pxl_prop.append(fragch_pxl_freq[i]/fgrnd_AB * 100)
        
        # Create the colormap
        cmap_path = TEMPL_DIR / "frag_change_colormap.txt"
        colors, _ = utils.get_colormap(cmap_path)
        bar_colors = [colors.get(100-v) for v in pixel_values]

        # Create the figure with bar chart
        fig, ax = plt.subplots(figsize=(7, 6))
        ax.bar(pixel_values, frag_chag_pxl_prop, color=bar_colors, width=1.0,
                      edgecolor='black', linewidth=0.4)

        # Formatting the Axes
        ax.set_xlabel('Change in connectivity [%]', fontsize=14)
        ax.set_ylabel('Frequency [%]', fontsize=14)
        ax.set_title('Connectivity change histogram', fontsize=15, pad=20)
        ax.tick_params(axis='both', which='major', labelsize=12)

        # Set X-axis limits and ticks (show every 10 units for clarity)
        ax.set_xlim(-41, 41)
        ax.set_xticks(range(-40, 41, 10))

        # Plotting
        plt.tight_layout()
        png_file = out_dir / f'{out_name}.png'
        plt.savefig(png_file, dpi=300, facecolor='white', transparent=False)
        plt.close()

        ### TXT Template Reporting ###
        content = {
            "input_file1": tiff1.name,
			"input_file2": tiff2.name,
            "epsg_code": minfo["epsg"],
            "unit_type": 'metres' if minfo["is_projected"] else 'degrees',
            "resolx": minfo["resX"],
            "resoly": minfo["resY"],
            "rows_val": minfo["rows"],
            "cols_val": minfo["cols"],
            "tot_pxl": minfo["rows"] * minfo["cols"],
			
            "foreg_pxl_A": fgrnd_A,
            "backg_pxl_A": bgrnd_A,
            "spec3_pxl_A": bgsp3_A,
            "spec4_pxl_A": bgsp4_A,
			"miss_pxl_A": miss_A,
            "foreg_pxl_B": fgrnd_B,
            "backg_pxl_B": bgrnd_B,
            "spec3_pxl_B": bgsp3_B,
            "spec4_pxl_B": bgsp4_B,
			"miss_pxl_B": miss_B,

            "used_method": method,
            "window_size": window_size,
            "window_areaHA": f"{(window_size**2)*minfo['resX']*minfo['resY']/10000:.4f}" if minfo["is_projected"] else '--',
            "window_areaAC": f"{(window_size**2)*minfo['resX']*minfo['resY']*0.000247105:.4f}" if minfo["is_projected"] else '--',

            "output_file": f"{out_name}.tif",

			"fg_valA": f"{fgrnd_A:>9}",
			"bg_valA": f"{bgrTT_A:>9}",
			"ms_valA": f"{miss_A:>9}",
			"fg_valB": f"{fgrnd_B:>9}",
			"bg_valB": f"{bgrTT_B:>9}",
			"ms_valB": f"{miss_B:>9}",
			"fg_ch": f"{fgrnd_B - fgrnd_A:>9}",
			"bg_ch": f"{bgrTT_B - bgrTT_A:>9}",
			"ms_ch": f"{miss_B - miss_A:>9}",
			
			"LM_00": f"{ch_matrix_land[0,0]:>9}",
			"LM_10": f"{ch_matrix_land[1,0]:>9}",
			"LM_20": f"{ch_matrix_land[2,0]:>9}",
			"LM_01": f"{ch_matrix_land[0,1]:>9}",
			"LM_11": f"{ch_matrix_land[1,1]:>9}",
			"LM_21": f"{ch_matrix_land[2,1]:>9}",
			"LM_02": f"{ch_matrix_land[0,2]:>9}",
			"LM_12": f"{ch_matrix_land[1,2]:>9}",
			"LM_22": f"{ch_matrix_land[2,2]:>9}",
            "Uarea": Uarea_AB,
			
			"R_valA": f"{rare_A:>9}",
			"P_valA": f"{patchy_A:>9}",
			"T_valA": f"{trans_A:>9}",
			"D_valA": f"{domin_A:>9}",
			"I_valA": f"{inter_A:>9}",
			"R_valB": f"{rare_B:>9}",
			"P_valB": f"{patchy_B:>9}",
			"T_valB": f"{trans_B:>9}",
			"D_valB": f"{domin_B:>9}",
			"I_valB": f"{inter_B:>9}",
			"R_ch": f"{rare_B - rare_A:>9}",
			"P_ch": f"{patchy_B - patchy_A:>9}",
			"T_ch": f"{trans_B - trans_A:>9}",
			"D_ch": f"{domin_B - domin_A:>9}",
			"I_ch": f"{inter_B - inter_A:>9}",	
			
			"diag_val": diagonal,
			"up_dw_val": f"{increase + decrease}",
			"up_val": increase,
			"dw_val": decrease,
			
			"AV_valA": f"{avcon_A:7.4f}",
			"FD_valA": f"{fad_av_A:7.4f}",
			"AV_valB": f"{avcon_B:7.4f}",
			"FD_valB": f"{fad_av_B:7.4f}",
			"AV_abs": f"{avcon_B - avcon_A:7.4f}",
			"FD_abs": f"{fad_av_B - fad_av_A:7.4f}",
			"AV_rel": f"{(avcon_B - avcon_A)/avcon_A:7.4f}",
			"FD_rel": f"{(fad_av_B - fad_av_A)/fad_av_A:7.4f}",
			
			"HD_val": f"{H_decr:>9}",
			"MD_val": f"{M_decr:>9}",
			"LD_val": f"{L_decr:>9}",
			"IN_val": f"{Insign:>9}",
			"LI_val": f"{L_incr:>9}",
			"MI_val": f"{M_incr:>9}",
			"HI_val": f"{H_incr:>9}",
			"HD_rel": f"{(H_decr/fgrnd_AB)*100:7.4f}",
			"MD_rel": f"{(M_decr/fgrnd_AB)*100:7.4f}",
			"LD_rel": f"{(L_decr/fgrnd_AB)*100:7.4f}",
			"IN_rel": f"{(Insign/fgrnd_AB)*100:7.4f}",
			"LI_rel": f"{(L_incr/fgrnd_AB)*100:7.4f}",
			"MI_rel": f"{(M_incr/fgrnd_AB)*100:7.4f}",
			"HI_rel": f"{(H_incr/fgrnd_AB)*100:7.4f}",
        }

        matrix_dict = {f"CM_{c}{r}": f"{ch_matrix_clas[c, r]:>9}" for r in range(6) for c in range(6)}
        content.update(matrix_dict)

        txt_file = out_dir / f'{out_name}.txt'
        utils.generate_text_report(TEMPL_DIR / 'frag_change_templ.txt', txt_file, content)

    # Statistic dictionaries
    path_stats_dict = None
    if out_file:
        path_stats_dict = {
            "path tif" : str(out_dir / f"{out_name}.tif"),
            "path txt" : str(txt_file),
            "path csv" : str(csv_file),
            "path png" : str(png_file)}
    input_stats_dict = {
        "A foregr pxl" : fgrnd_A,
        "A backgr pxl" : bgrnd_A,
        "A backgr3 pxl" : bgsp3_A,
        "A backgr4 pxl" : bgsp4_A,
        "A missing pxl" : miss_A,
        "B foregr pxl" : fgrnd_B,
        "B backgr pxl" : bgrnd_B,
        "B backgr3 pxl" : bgsp3_B,
        "B backgr4 pxl" : bgsp4_B,
        "B missing pxl" : miss_B}
    class_freq = {
        "A1 rare pxl" : rare_A,
        "A2 patch pxl" : patchy_A,
        "A3 trans pxl" : trans_A,
        "A4 domin pxl" : domin_A,
        "A5 inter pxl" : inter_A,
        "B1 rare pxl" : rare_B,
        "B2 patch pxl" : patchy_B,
        "B3 trans pxl" : trans_B,
        "B4 domin pxl" : domin_B,
        "B5 inter pxl" : inter_B}
    change_freq = {
        "1 Frag High decrease" : H_decr,
        "2 Frag Medium decrease" : M_decr,
        "3 Frag Low decrease" : L_decr,
        "4 Insign/no change" : Insign,
        "5 Frag Low increase" : L_incr,
        "6 Frag Medium increase" : M_incr,
        "7 Frag High increase" : H_incr}
    output_stats_dict = {
        "class freq" : class_freq,
        "Frag change freq" : change_freq,
        "Land change matrix" : ch_matrix_land,
        "Class change matrix" : ch_matrix_clas,
        "A fad_av" : fad_av_A,
        "A avcon" : avcon_A,
        "B fad_av" : fad_av_B,
        "B avcon" : avcon_B}
    stats_dict = {
        "output paths" : path_stats_dict,
        "input stats" : input_stats_dict,
        "output stats" : output_stats_dict}

    return stats_dict


#####

def aggregate_change_matrix(matrix, groupings):
    """Aggregates a change matrix and calculates the totals for File A and File B.

    Parameters:
    - matrix (np.ndarray): The original square matrix (e.g., 11x11).
    - groupings (list of lists): The custom class groupings.

    Returns:
    - new_matrix (np.ndarray): The aggregated square matrix.
    - file_a_totals (np.ndarray): Total pixels per group in File A (Row sums).
    - file_b_totals (np.ndarray): Total pixels per group in File B (Col sums).
    """
    num_new_classes = len(groupings)
    new_matrix = np.zeros((num_new_classes, num_new_classes), dtype=matrix.dtype)

    # 1. Compute the aggregated matrix
    for new_row, row_indices in enumerate(groupings):
        for new_col, col_indices in enumerate(groupings):
            sub_matrix = matrix[np.ix_(row_indices, col_indices)]
            new_matrix[new_row, new_col] = sub_matrix.sum()

    # 2. Calculate totals directly from the newly aggregated matrix
    # Axis 1 sums across columns (collapsing rows -> File A totals)
    file_a_totals = new_matrix.sum(axis=1)

    # Axis 0 sums down rows (collapsing columns -> File B totals)
    file_b_totals = new_matrix.sum(axis=0)

    return new_matrix, file_a_totals, file_b_totals