name: Compile JOSS Paper
on:
  push:
    branches:
      - joss-paper

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Build Paper PDF
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Paper using Inara
        uses: openjournals/openjournals-action@main
        with:
          journal: joss
                     # This points to your paper folder structure
          paper-path: paper/paper.md